### ISSUE TITLE
Pick a new game theory reference book

### ISSUE THREAD

**Issue by karlfloersch** [game-theory/research#2]
In our last discussion we determined that our current textbook doesn't fit our needs. The issues identified were:
1. Non-standard / confusing notation
2. No solutions provided for the exercises

# Alternatives
### [Game Theory: An Introduction](https://drive.google.com/file/d/0Byw_CYbPDsDEal9WNGJiTVdHODg/view)
@kidwai recommended this as a possible replacement. Some reasons @kidwai gave to read the book were:
- This version includes solutions to problems
- [Here](https://www.dal.ca/content/dam/dalhousie/pdf/faculty/science/math-stats/syllabi/MATH%203400%20-%20Fall%20term.pdf) is the syllabus for the course I used this in.
- well-written, with sensible notation and uniformity across definitions, theorems, proofs
- replaces extensive linear programming background with maple commands
- lots of examples and pictures
- only 100 pages - good to get an introduction to major aspects of the theory prior to focusing on a specific topic (although a more focused book with a self-contained primer could also be useful)

**Comment by karlfloersch** [comment]
@kidwai when you say:
> only 100 pages

what are you referring to? The `pdf` you included seems to be around 500 pages long. Do you mean the introduction?

**Comment by kidwai** [comment]
@karlfloersch ah, I had actually noted the length only in the [first edition](http://webpages.math.luc.edu/~enb/gamebook.pdf). I guess the second edition has some extra material, exercises, and different printing that increases this significantly.

**Comment by kjekac** [comment]
I've read bits and pieces of the proposed book in order to evaluate it. I can say that I definitely prefer it to the one we've been using so far, and I don't have any other suggestion, so my opinion at this point is that we should switch to it. (Having a syllabus should definitely be beneficial, too.)

**Comment by karlfloersch** [comment]
I agree. From what I've read this book is much clearer and I like their example driven approach.

@kidwai Did you mentioned that this book includes implementations of algorithms using [Maple](http://www.maplesoft.com/)? It would be super awesome if that's the case.

**EDIT**: Whoops, found it. At the end of each section they have implementations using Maple / Mathematica! Super cool!

**EDIT 2**: Should I/we buy Maple or Mathematica or something else? Both are of course quite expensive. [**EDIT 3**:] Started playing around with https://develop.open.wolframcloud.com/app/ -- pretty cool and seems to be free! But I generally hate how it isn't OSS. Maybe Python/Haskell/ something more open is the way to go? Maybe better to discuss on issue https://github.com/game-theory/research/issues/1

**Comment by MrChico** [comment]
I'm a fan of this book! This passage cracked me up

> I will end this introduction with an intriguing quote that Professor Avner Friedman included in his book Differential Games that he had me read for my graduate studies. The quote is from Lord Byron: “There are two pleasures for your choosing; the first is winning and the second is losing.” Is losing really a pleasure? I can answer this now. The answer is no.
